# Generated by Django 4.1 on 2022-09-26 00:51

import datetime
from operator import mod
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0003_log"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chore",
            old_name="repeat_interval",
            new_name="due_duration",
        ),
        migrations.AlterField(
            model_name="chore",
            name="due_duration",
            field=models.DurationField(verbose_name="Due Duration"),
        ),
        migrations.AddField(
            model_name="chore",
            name="overdue_duration",
            field=models.DurationField(
                default=datetime.timedelta(), verbose_name="Overdue Duration"
            ),
            preserve_default=False,
        ),
    ]
