# Generated by Django 4.1 on 2022-10-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0004_chore_due_duration_and_overdue_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chore",
            name="overdue_duration",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Overdue Duration"
            ),
        ),
    ]
