# Generated by Django 4.1 on 2022-11-17 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chores", "0006_category_chore_category"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Tag",
        ),
        migrations.RemoveField(
            model_name="chore",
            name="category",
        ),
        migrations.AddField(
            model_name="chore",
            name="tags",
            field=models.ManyToManyField(blank=True, to="chores.tag"),
        ),
    ]
