# Generated by Django 4.1 on 2022-11-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0007_rename_category_tag_remove_chore_category_chore_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chore",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
    ]
