name: Test

on: [push, pull_request]

jobs:
  test:
    name: Run Django Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: pipenv install --dev
      - name: Run tests
        run: pipenv run python manage.py test
